version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile_node
    volumes:
      - ./volumes3:/usr/src/app
    command: sh -c "cd react-app && yarn start"
    ports:
      - "3000:3000"
